title: Spyglass Archive
email: pronoun.nationstates@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    View an archive of Spyglass sheets from previous days.
baseurl: '/spyglass-archive' # the subpath of your site, e.g. /blog
url: 'https://esfalsa.github.io' # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: esfalsa

collections:
  sheets:
    output: true
    permalink: /:collection/:name

# Build settings
# theme: minima
plugins:
    - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
