title: Spyglass Archive
email: pronoun.nationstates@gmail.com
description: View an archive of Spyglass sheets from previous days.

baseurl: '/spyglass-archive'
url: 'https://esfalsa.github.io'

github_username: esfalsa
repository: esfalsa/spyglass-archive
github:
  source:
    branch: main

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: pages-themes/primer@v0.6.0
