name: Download Spyglass Sheet
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  download-spyglass-sheet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: python Spyglass-cli.py -n Esfalsa
    - run: echo "DATE=$(date --date="yesterday" +"%b %d %Y")" >> ${GITHUB_ENV}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Spyglass ${{ env.DATE }}